apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: app.rules
      rules:
        - alert: WorkerHighEventLoopLag
          expr: nodejs_eventloop_lag_seconds{namespace="monitoring-app"} > 0.1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Worker Event Loop Lag is high"
            description: "Event loop lag on {{ $labels.pod }} is {{ $value }}s"
