apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: monitoring-app
  labels:
    app: microservices
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /submit
            pathType: Prefix
            backend:
              service:
                name: api-gateway-svc
                port:
                  number: 80
          - path: /status
            pathType: Prefix
            backend:
              service:
                name: api-gateway-svc
                port:
                  number: 80
          - path: /stats
            pathType: Prefix
            backend:
              service:
                name: stats-service-svc
                port:
                  number: 3002